default:
  image: python:3-slim
stages:
  - test
  - publish
  - deploy

test:
  stage: test
  script:
   - pip install -r testing_requirements.txt
   - nosetests --with-coverage --cover-package=apiserver --cover-xml
  artifacts:
    reports:
      cobertura: coverage.xml

deploy:
  stage: deploy
  script:
    - echo "Doing nothing for now"

publishgit-do:
  image: python:3-slim
  stage: publish
  only:
    - tags
  tags: [stable]
  script:
  - apt-get update 
  - apt-get install -y git
  - git remote set-url gith "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/eflows4hpc/datacatalog.git"
  - git remote -v
  - git push -u gith stable

