default:
  image: python:3-slim

# stages:
#   - test
#   - pages
# test:
#   script:
#    - pip install -r requirements.txt
#    - pytest 

pages:
  cache: {}
  stage: deploy
  script:
  - echo "Deployment starting..."
  - pip install -r requirements.txt
  - python frontend/createStatic.py
  # - docker build -t datacatalog-apiserver ./apiserver
  # - docker run -d --name my_container -p 127.0.0.1:8080:80 datacalog-apiserver
  - mkdir public
  - cp -r site/* public/
  - echo "Deployment finished"
  artifacts:
    paths:
    - public
  only:
    - mptest
