default:
  image: python:3-slim

stages:
  - test
  - build
  - deploy

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script: 
   - pip install -r testing_requirements.txt
   - nosetests --with-coverage --cover-package=apiserver

build:sites:
  cache: {}
  stage: build
  script:
    - python frontend/createStatic.py
    - echo "static web content has been created"
  artifacts:
    paths:
      - site

pages:
  cache: {}
  stage: deploy
  image: docker:latest
  dependencies:
    - build:sites
  script:
  - echo "Deployment starting..."
  - docker build -t datacatalog-apiserver ./apiserver
  - docker run -d --name my_container -p 127.0.0.1:8080:80 datacalog-apiserver
  # - mkdir public
  # - cp -r site/* public/
  - echo "Deployment finished. Missing API server"
  # - uvicorn apiserver:app --reload --reload-dir apiserver
  artifacts:
    paths:
    - public
  only:
    - mptest
