default:
  image: python:3-slim

stages:
  - test
  - build
  - deploy

# before_script:
#   - pip install -r requirements.txt

test:
  stage: test
  script: 
   - pip install -r testing_requirements.txt
   - nosetests --with-coverage --cover-package=apiserver

build:sites:
  cache: {}
  stage: build
  script:
    - pip install -r requirements.txt
    - python frontend/createStatic.py
    - echo "static web content has been created"
  artifacts:
    paths:
      - site

pages:
  cache: {}
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    APP_VERSION: "0.0.1"
    MOUNT_POINT: /builds/$CI_PROJECT_PATH/mnt
  services:
  - docker:20.10.7
  dependencies:
    - build:sites
  script:
  - echo "Deployment starting..."
  - mkdir -p "$MOUNT_POINT"
  - docker build -f ./apiserver/Dockerfile -t $CI_REGISTRY_IMAGE:$APP_VERSION .
  - docker run -d --name my_container -p https://rybicki1.pages.jsc.fz-juelich.de/datacatalog/ -d $CI_REGISTRY_IMAGE:$APP_VERSION
  # - mkdir public
  # - cp -r site/* public/
  - echo "Deployment finished. Missing API server"
  # - uvicorn apiserver:app --reload --reload-dir apiserver
  artifacts:
    paths:
    - public
  only:
    - mptest
