default:
  image: python:3-slim

stages:
  - test
  - build
  - deploy

# before_script:
#   - pip install -r requirements.txt

test:
  stage: test
  script: 
   - pip install -r testing_requirements.txt
   - nosetests --with-coverage --cover-package=apiserver

build:sites:
  cache: {}
  stage: build
  script:
    - pip install -r requirements.txt
    - python frontend/createStatic.py
    - echo "static web content has been created"
  artifacts:
    paths:
      - site

pages:
  cache: {}
  stage: deploy
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
  - docker:19.03.5-dind
  dependencies:
    - build:sites
  script:
  - echo "Deployment starting..."
  - docker build -t datacatalog-apiserver -f ./apiserver/Dockerfile .
  - docker run -d --name my_container -p https://rybicki1.pages.jsc.fz-juelich.de/datacatalog/ datacalog-apiserver
  # - mkdir public
  # - cp -r site/* public/
  - echo "Deployment finished. Missing API server"
  # - uvicorn apiserver:app --reload --reload-dir apiserver
  artifacts:
    paths:
    - public
  only:
    - mptest
