default:
  image: python:3-slim

job 1:
  stage: test
  tags:
   - public-docker
  image: docker:latest
  script:
   - echo "Logging in"
   - docker --version
   - docker login gitlab.version.fz-juelich.de:5555 -u rybicki1 -p ldalda
   - docker image ls
