version: "3.7"

services:

    reverse-proxy:
        image: "registry.jsc.fz-juelich.de/rybicki1/datacatalog/nginx-proxy"
        container_name: "reverse-proxy"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/tmp/docker.sock:ro"
            - "static:/var/www/html/static/"
        restart: "always"
        networks: 
            - "net"
        ports:
            - "80:80"
            - "443:443"

    letsencrypt:
        image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
        container_name: "letsencrypt-helper"
        volumes:
            - "html:/usr/share/nginx/html"
            - "dhparam:/etc/nginx/dhparam"
            - "vhost:/etc/nginx/vhost.d"
            - "certs:/etc/nginx/certs"
            - "/run/docker.sock:/var/run/docker.sock:ro"
        environment:
            NGINX_PROXY_CONTAINER: "reverse-proxy"
            DEFAULT_EMAIL: "c.boettcher@fz-juelich.de"
        restart: "always"
        depends_on:
            - "reverse-proxy"
        networks: 
            - "net"
    datacatalog-apiserver:
        image: "registry.jsc.fz-juelich.de/rybicki1/datacatalog:latest"
        container_name: "datacatalog-apiserver"
        volumes:
            - "userdb:/app/userdb.json"
            - "appdata:/app/data"
        environment:
            VIRTUAL_HOST: zam10028.zam.kfa-juelich.de
            LETSENCRYPT_HOST: zam10028.zam.kfa-juelich.de
            VIRTUAL_PORT: 8000
volumes:
    certs:
    html:
    vhost:
    dhparam:
    static:
    userdb:
    appdata:
    
networks:
    net:
        external: true
       